### ISSUE TITLE
After today's update, device only boots to fastboot, not even to recovery

### ISSUE THREAD

**Issue by Moini** [LineageOS/android_device_motorola_payton#1]
Hi - I hope this is the right place to report this.

Today, I was notified of an update (my very first LineageOS update, I installed it on my (new) Moto X4 just a couple of days ago). I downloaded, installed and rebooted.

Since reboot, all I get is the fastboot bootloader that refuses to do anything useful. It even looks different from what it looked like at the beginning (no android bot image, just text).
I can read the boot log (nothing specific in it, except that it failed to boot into xyz, can select to boot into various modes (recovery, bq, and some more), but all of those fail. 

I can't connect via adb (it doesn't find the device). I can connect via fastboot, which finds the device, but it still doesn't boot from the twrp image which had worked before (a very helpful message about an Error loading it is issued...).

TWRP should be somewhere on the device (theoretically, it should be the recovery system), plus a really recent LineageOS. Also, before I flashed Lineage, I have made a backup of all partitions of the device. 

[Edit] ~~except for system (which refused to be backed up with TWRP) - but I have systemimg~~ (this was before I reformatted the SD card as ext4, after that, I was able to backup all partitions).

I also cannot turn the device off. As soon as I try, either by selecting Poweroff, or by long-pressing the power button, it reboots (Motorola screen > fastboot in text mode).

**Comment by viggy96** [comment]
I have experienced the same issue. I used the updater to update from build 2 March 2019, to the 3 March 2019 build, and after the updater had completed its job, I rebooted the device. Then, the device would not boot to the OS, and would simply boot to a black screen by default. I then rebooted to the bootloader. 

I have noticed that upon rebooting to the bootloader, the device reports that the bootloader is locked, even though I did no such thing on my own. It appears that the device locked the bootloader on its own, and will no longer allow any third party software to boot. I am also unable to re-unlock the bootloader with the official instructions from Motorola. The device will no boot TWRP, or the OS. I am only able to access the bootloader. When I try to boot TWRP, with `fastboot boot`, I get a permission denied error, since the bootloader is locked. 

Any help on this issue would be greatly appreciated. I hope that this can be fixed in the coming days.

**Comment by p-ho** [comment]
Have you already tried to reflash the bootloader using blank flash?

cf.
https://forum.xda-developers.com/moto-x4/help/hard-bricked-how-enter-emergency-t3757472

Am 04.03.19 um 05:21 schrieb Vignesh Balasubramaniam:

**Comment by viggy96** [comment]
The maintainer suggested flashing gpt.bin, which he provided, and it worked. However the bug still exists, and the maintainer is aware. Payton builds have been taken down in the meantime, and future builds are to be stopped until this bug is fixed.

**Comment by ajs124** [comment]
Seeing as the builds are bag up, is this still valid for you?

I'm running a custom build of LineageOS-16.0 on my payton, which seems to be working fine, so far.

**Comment by viggy96** [comment]
@ajs124 The problems have been fixed by the latest builds.

**Comment by daedroza** [comment]
Please close this issue.

**Comment by Moini** [comment]
There's a button. Anyone can close an issue. Doing so for you now :)

**Comment by Moini** [comment]
(Sorry, didn't remember I had actually posted this)
